program_version: 1.0.0
file_version: 1.0
game_version: HD
seed: ClearStiffFarore
progression_dungeons: Race Mode
progression_great_fairies: true
progression_puzzle_secret_caves: true
progression_combat_secret_caves: true
progression_short_sidequests: true
progression_long_sidequests: false
progression_spoils_trading: false
progression_minigames: false
progression_free_gifts: true
progression_mail: true
progression_platforms_rafts: true
progression_submarines: true
progression_eye_reef_chests: false
progression_big_octos_gunboats: true
progression_triforce_charts: false
progression_treasure_charts: false
progression_expensive_purchases: true
progression_misc: true
progression_tingle_chests: false
progression_battlesquid: true
progression_savage_labyrinth: true
progression_island_puzzles: true
progression_dungeon_secrets: false
progression_obscure: false
randomize_charts: true
randomize_starting_island: true
randomize_dungeon_entrances: true
randomize_boss_entrances: true
randomize_miniboss_entrances: false
randomize_cave_entrances: Disabled
randomize_door_entrances: false
randomize_misc_entrances: false
mix_dungeons: false
mix_bosses: false
mix_minibosses: false
mix_caves: false
mix_doors: false
mix_misc: false
decouple_entrances: false
ho_ho_hints: false
korl_hints: true
clearer_hints: true
use_always_hints: false
path_hints: 2
barren_hints: 2
item_hints: 2
location_hints: 2
instant_text_boxes: true
fix_rng: true
performance: false
reveal_full_sea_chart: true
add_shortcut_warps_between_dungeons: false
skip_rematch_bosses: true
invert_sea_compass_x_axis: false
num_required_dungeons: 3
damage_multiplier: 3
chest_type_matches_contents: true
remove_swords: false
starting_pohs: 0
starting_hcs: 1
starting_joy_pendants: 0
starting_skull_necklaces: 0
starting_boko_baba_seeds: 0
starting_golden_feathers: 0
starting_knights_crests: 0
starting_red_chu_jellys: 0
starting_green_chu_jellys: 0
starting_blue_chu_jellys: 0
remove_music: false
do_not_generate_spoiler_log: false
start_with_random_item: false
random_item_slide_item: false
classic_mode: true
plandomizer: false
dungeon_small_keys: Own Dungeon
dungeon_big_keys: Own Dungeon
dungeon_maps_compasses: Own Dungeon
starting_gear:
  - Ballad of Gales
  - Progressive Sail
  - Song of Passing